#!/bin/bash

echo "Running performance tests and organizing CSV files..."

# Test class names
TESTS=(
    "TodoTasksofTests"
    "TodoCategoriesTests"
    "ProjectTasksTests"
    "ProjectCategoriesTests"
    "CategoryProjectsTests"
    "CategoryTodosTests"
)

# Output folder structure
MAIN_DIR="csv_files"
SUB_DIR="interoperability_csv"
OUTPUT_DIR="$MAIN_DIR/$SUB_DIR"

# Create CSV folder
mkdir -p "$OUTPUT_DIR"

for TEST in "${TESTS[@]}"; do

    echo "----------------------------------------------------"
    echo "Running $TEST"
    echo "----------------------------------------------------"

    # Run test normally
    mvn -q -Dtest="$TEST" test

    # Move CSV file generated by this test
    CSV_FILE=$(ls *_metrics.csv 2>/dev/null | head -n 1)

    if [[ -n "$CSV_FILE" ]]; then
        echo "Moving $CSV_FILE → $OUTPUT_DIR/"
        mv "$CSV_FILE" "$OUTPUT_DIR/"
    else
        echo "⚠ No CSV file found for $TEST — did the test run correctly?"
    fi

    echo "✔ Finished $TEST"
    echo
done

echo "====================================================="
echo "All CSV files saved to: $OUTPUT_DIR/"
echo "====================================================="
