#!/bin/bash

# PART 1 — Interoperability Tests (CSV only)


echo "Running interoperability performance tests and saving CSV files..."

# Interoperability Test class names
INTER_TESTS=(
    "TodoTasksofTests"
    "TodoCategoriesTests"
    "ProjectTasksTests"
    "ProjectCategoriesTests"
    "CategoryProjectsTests"
    "CategoryTodosTests"
)

# CSV output directory
MAIN_DIR="csv_files"
SUB_DIR="interoperability_csv"
OUTPUT_DIR="$MAIN_DIR/$SUB_DIR"

mkdir -p "$OUTPUT_DIR"

for TEST in "${INTER_TESTS[@]}"; do

    echo "Running $TEST"

    # Run test (console output is displayed normally)
    mvn -q -Dtest="$TEST" test

    # Move CSV file generated by this test
    CSV_FILE=$(ls *_metrics.csv 2>/dev/null | head -n 1)
    if [[ -n "$CSV_FILE" ]]; then
        echo "Moving $CSV_FILE → $OUTPUT_DIR/"
        mv "$CSV_FILE" "$OUTPUT_DIR/"
    else
        echo "⚠ No CSV file found for $TEST — did the test run correctly?"
    fi

    echo "✔ Finished $TEST"
    echo
done

echo "Interoperability CSV files saved to: $OUTPUT_DIR/"



# PART 2 — Basic Tests (category / project / todo)


echo "Running basic performance tests (Category, Project, Todo)..."

BASIC_TESTS=(
    "CategoryTests"
    "ProjectTests"
    "TodoTests"
)

BASE_DIR="csv_files"
mkdir -p "$BASE_DIR"

for TEST in "${BASIC_TESTS[@]}"; do

    echo "Running $TEST"

    mvn -q -Dtest="$TEST" test

    TEST_DIR="$BASE_DIR/$TEST"
    mkdir -p "$TEST_DIR"

    CSV_FILE=$(ls *_metrics.csv 2>/dev/null | head -n 1)

    if [[ -n "$CSV_FILE" ]]; then
        echo "Saving CSV: $CSV_FILE → $TEST_DIR/"
        mv "$CSV_FILE" "$TEST_DIR/"
    else
        echo "⚠ No CSV file found for $TEST"
    fi

    echo "✔ Finished $TEST"
    echo
done

echo "All basic CSV files saved under: $BASE_DIR/"



# PART 3 — Run Python graph generator


echo "Activating venv and generating graphs..."
source venv/bin/activate
python graph_all.py

echo "All graphs completed."
