#!/bin/bash


# PART 1 — Interoperability Tests (with TXT logs)


echo "Running interoperability performance tests and organizing CSV + TXT files..."

# Interoperability Test class names
INTER_TESTS=(
    "TodoTasksofTests"
    "TodoCategoriesTests"
    "ProjectTasksTests"
    "ProjectCategoriesTests"
    "CategoryProjectsTests"
    "CategoryTodosTests"
)

# Folder structure
MAIN_DIR="csv_files"
SUB_DIR="interoperability_csv"
OUTPUT_DIR="$MAIN_DIR/$SUB_DIR"

TXT_MAIN_DIR="data_txt"
TXT_SUB_DIR="interoperability_txt"
TXT_OUTPUT_DIR="$TXT_MAIN_DIR/$TXT_SUB_DIR"

# Create directories
mkdir -p "$OUTPUT_DIR"
mkdir -p "$TXT_OUTPUT_DIR"

for TEST in "${INTER_TESTS[@]}"; do

    OUTFILE="${TEST}.txt"

    echo "Running $TEST  ->  saving console output to $OUTFILE"

    rm -f "$OUTFILE"

    # Run test and capture console output
    mvn -q -Dtest="$TEST" test > "$OUTFILE" 2>&1

    mv "$OUTFILE" "$TXT_OUTPUT_DIR/"

    # Move CSV file generated by this test
    CSV_FILE=$(ls *_metrics.csv 2>/dev/null | head -n 1)
    if [[ -n "$CSV_FILE" ]]; then
        echo "Moving $CSV_FILE → $OUTPUT_DIR/"
        mv "$CSV_FILE" "$OUTPUT_DIR/"
    else
        echo " No CSV file found for $TEST — did the test run correctly?"
    fi

    echo "✔ Finished $TEST"
    echo
done

echo "Interoperability CSV files saved to: $OUTPUT_DIR/"
echo "Interoperability TXT logs saved to: $TXT_OUTPUT_DIR/"


# PART 2 — Regular Tests (category / project / todo)

echo "Running basic performance tests (Category, Project, Todo) and organizing CSV..."

# Basic Tests
BASIC_TESTS=(
    "CategoryTests"
    "ProjectTests"
    "TodoTests"
)

# Base directory for CSV output
BASE_DIR="csv_files"
mkdir -p "$BASE_DIR"

for TEST in "${BASIC_TESTS[@]}"; do

    echo "Running $TEST"

    # Run test
    mvn -q -Dtest="$TEST" test

    # Folder for this test
    TEST_DIR="$BASE_DIR/$TEST"
    mkdir -p "$TEST_DIR"

    # Move CSV file
    CSV_FILE=$(ls *_metrics.csv 2>/dev/null | head -n 1)
    if [[ -n "$CSV_FILE" ]]; then
        echo "Saving CSV: $CSV_FILE → $TEST_DIR/"
        mv "$CSV_FILE" "$TEST_DIR/"
    else
        echo "No CSV file found for $TEST"
    fi

    echo "Finished $TEST"
    echo
done

echo "All regular CSV files saved under: $BASE_DIR/"

source venv/bin/activate
python graph_all.py

echo "All graphs completed."